# -*- coding: utf-8 -*-
"""coffee_shop_sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M-HUVHXD08qRJLZjyAZC7hA-Cdlu9YBR
"""

import pandas as pd

df = pd.read_csv("/content/coffee_shop_sales.csv")
df.info()

df.head()

df.isnull().sum()

df['customer_age_group'].fillna("Unknown", inplace=True)
df['customer_gender'].fillna("Unknown", inplace=True)
df['weather_condition'].fillna("Unknown", inplace=True)
df['holiday_name'].fillna("No Holiday", inplace=True)

df['temperature_c'].fillna(df['temperature_c'].mean(), inplace=True)

df.isnull().sum()

df.columns = df.columns.str.lower().str.strip()

df['timestamp'] = pd.to_datetime(df['timestamp'])

df['hour'] = df['timestamp'].dt.hour
df['day'] = df['timestamp'].dt.day_name()
df['month'] = df['timestamp'].dt.month

df.describe()

from google.colab import files

df.to_csv("clean_data.csv", index=False)  # احفظ الملف أولاً
files.download("clean_data.csv")          # حمّل الملف على جهازك